### ISSUE TITLE
Selection of UI elements after leaving fullscreen in i3WM

### ISSUE THREAD

**Issue by ottojo** [SoPra-Team-17/Client#116]
Steps to reproduce:
* Start game in tabbed mode
* fullscreen game (Super-F)
* leave fullscreen
* fullscreen again

Action selection and menu button are not clickable anymore.

Problem does not occur when using floating mode (without fullscreen). Tiling mode without fullscreen could not be tested because UI gets cropped.

**Comment by Marco5de** [comment]
Kannst du bei dir mal testen, ob wenn du im controller/Controller.py das `pygame.RESIZEABLE` durch ein `pygame.FULLSCREEN` ersetzt, noch alles geht?

Das Problem da ist, dass da ein Resize event getriggert wird, das kann man dann behandeln und die Sachen neu setzen. Dann geht aber bei unsrer UI-einiges kaputt.
Da ich am Ende eigentlich sowieso nur Fullscreen haben will, wäre das cool wenn du das mal testen könntest.

**Comment by ottojo** [comment]
Hört sich nach solider Lösung an, ist aber ein bisschen arg broken auf multimonitor setup, das öffnet sich so in der oberen hälfte des anderen bildschirms...
