### ISSUE TITLE
Performance Probleme

### ISSUE THREAD

**Issue by Marco5de** [SoPra-Team-17/Client#12]
Bspw. bei 100x100 = 10000 Blöcken gibt es aktuell noch etwas Probleme. Um das ganze zu verbessern sollten die folgenden Features implementiert werden
* ~im Moment werden die Assets/Bilder für jeden Block geladen, das sollte für jedes Model nur einmal an einem zentralen Ort geschehen~ **DONE**
* ~es werden immer alle Blöcke gezeichnet, auch wenn diese nicht innerhalb des sichtbaren Bildschrims sind, es sollte also eine Funktion geschrieben wird, welche vor dem Zeichnen checkt ob die Screen Coordinaten innerhalb des Windows sind~  
~Triviale Implementierung bringt keinen Vorteil. Da muss man sich was überlegen um von dem O(Blöcke) wegzukommen!~
* ~Wenn ein Block an einer gegeben Koordinate gefunden werden soll, wird derzeit die gesamte Liste durchlaufen --> O(n) ikann aber eigentlich eine O(1) Operation sein~

**Comment by Marco5de** [comment]
Man könnte sich noch überlegen, immer nur einen Teil des Spielfelds neu zu zeichnen. Da das Spiel recht statisch ist, ändert sich in den meisten Fällen (wenn die Kamera nicht bewegt wurde) sehr wenig.

**Comment by authaldo** [comment]
Der updated Marker im Field ist von den Servern nur optional zu unterstützen, würde sich aber falls er vorhanden ist dafür anbieten. 
Allerdings muss man zusätzlich noch die Charaktere durchgehen, da zumindest bei unserem Server das Updated nur gesetzt wird, wenn wirklich was am Zustand des Feldes passiert.

**Comment by Marco5de** [comment]
> Der updated Marker im Field ist von den Servern nur optional zu unterstützen, würde sich aber falls er vorhanden ist dafür anbieten.
> Allerdings muss man zusätzlich noch die Charaktere durchgehen, da zumindest bei unserem Server das Updated nur gesetzt wird, wenn wirklich was am Zustand des Feldes passiert.

Das ist nur bedingt sinnvoll, da das aktualisieren des Spielstatus nur ein sehr kleiner Teil des Gesamtaufwands ist.

**Comment by Marco5de** [comment]
Wird nicht mehr implementiert.
