### ISSUE TITLE
Server erhält keine GameLeave Message

### ISSUE THREAD

**Issue by authaldo** [SoPra-Team-17/Client#127]
Wenn während des Wartens auf den Beitritt eines zweiten Spielers auf Return geklickt wird, so erhält gelangt man zwar ins Hauptmenü, aber der Server erhält keine GameLeave Message. Außerdem bleibt ein anschließendes Klicken auf Start Game wirkungslos.

**Comment by Marco5de** [comment]
Gibt es bereits in LibClient issue zu, kümmer ich mich auf Client Seite drum.
