### ISSUE TITLE
Use C++ Libraries in Python

### ISSUE THREAD

**Issue by csacro** [SoPra-Team-17/Client#15]
Es gibt viele Möglichkeiten C++ Code in Python zu verwenden. Häufig muss man dafür in Eigenarbeit Wrapper schreiben.

Ich habe cppyy für Python gefunden, was einem die ganze Arbeit abnimmt und ein Beispiel dafür implementiert. Sieht für mich sehr praktikabel aus.

Wenn ihr andere Ideen habt, gerne.

**Comment by authaldo** [comment]
Ich finde das sieht echt vielversprechend aus. Gibt's da irgendwelche bekannten Limitierungen was den C++ Code angeht oder kann man da echt die ganze Bandbreite von C++ nutzen?

**Comment by csacro** [comment]
Irgendwelche Limitierungen wird es sicher geben. Ich hab bisher nur das im Branch ausprobiert.
Das was in der Feature Liste steht, sollte aber auf jeden Fall gehen (https://cppyy.readthedocs.io/en/latest/#)

**Comment by csacro** [comment]
see #16
