### ISSUE TITLE
MainMenu: Use State information from LibClient

### ISSUE THREAD

**Issue by Marco5de** [SoPra-Team-17/Client#67]
Wenn man sich mit dem Server verbindet und in er Lobby zum Hauptmenü zurück geht, kommt man nicht mehr in die Lobby, da man bereits verbunden ist.

**Comment by csacro** [comment]
Muss getestet werden: "State machine" von LibClient ist hierbei doch kein Problem. Wenn dann wirft die WebSocketCpp lib evtl. einen Fehler.

allgemeine Info: LibClient hat eine isConnected() Methode

**Comment by csacro** [comment]
fixe ich in LibClient auf dem Branch FixIsConnected
